Repository GoormBbang/CloudBread_server, pull requests merged in 2025-10, with the labels that each got.

#42 [Feat/#41] 음식 데이터 수정
  src/main/java/com/cloudbread/domain/food/domain/entity/Food.java
  src/main/java/com/cloudbread/global/db_seeder/food/FoodDataSeedService.java
Labels: ✏️ feature, 🔨 fix

#44 [feat/#39] 이번주차팁 전체/태아/임산부/영양 조회 작업 완료
  src/main/java/com/cloudbread/domain/crawling/application/CrawlingService.java
  src/main/java/com/cloudbread/domain/crawling/domain/repository/TipContentRepository.java
  src/main/java/com/cloudbread/domain/tip/api/UserTipController.java
  src/main/java/com/cloudbread/domain/tip/application/UserTipService.java
  src/main/java/com/cloudbread/domain/tip/application/UserTipServiceImpl.java
  src/main/java/com/cloudbread/domain/user/application/UserService.java
  src/main/java/com/cloudbread/domain/user/application/UserServiceImpl.java
  src/main/java/com/cloudbread/domain/user/dto/UserResponseDto.java
Labels: ✏️ feature

#45 [feat/#43] : 배포서버, food 데이터 시더 해결
  build.gradle
  src/main/java/com/cloudbread/global/db_seeder/food/FoodDataSeedService.java
Labels: ✏️ feature

#50 [Feat/#46] 오늘의ai추천식단생성/조회
  build.gradle
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/.DS_Store
  src/main/java/com/.DS_Store
  src/main/java/com/cloudbread/.DS_Store
  src/main/java/com/cloudbread/auth/oauth2/CustomOAuth2User.java
  src/main/java/com/cloudbread/domain/.DS_Store
  src/main/java/com/cloudbread/domain/food/api/FoodController.java
  src/main/java/com/cloudbread/domain/food/application/FoodService.java
  src/main/java/com/cloudbread/domain/food/application/FoodServiceImpl.java
  src/main/java/com/cloudbread/domain/mealplan/.DS_Store
  src/main/java/com/cloudbread/domain/mealplan/api/MealPlanController.java
  src/main/java/com/cloudbread/domain/mealplan/application/MealPlanService.java
  src/main/java/com/cloudbread/domain/mealplan/application/MealPlanServiceImpl.java
  src/main/java/com/cloudbread/domain/mealplan/client/FastApiMealPlanClient.java
  src/main/java/com/cloudbread/domain/mealplan/coverter/MealPlanConverter.java
  src/main/java/com/cloudbread/domain/mealplan/domain/.DS_Store
  src/main/java/com/cloudbread/domain/mealplan/domain/entity/MealPlan.java
  src/main/java/com/cloudbread/domain/mealplan/domain/entity/MealPlanItem.java
  src/main/java/com/cloudbread/domain/mealplan/domain/repository/MealPlanItemRepository.java
  src/main/java/com/cloudbread/domain/mealplan/domain/repository/MealPlanRepository.java
  src/main/java/com/cloudbread/domain/mealplan/dto/MealPlanRequestDto.java
  src/main/java/com/cloudbread/domain/mealplan/dto/MealPlanResponseDto.java
  src/main/java/com/cloudbread/domain/user/domain/entity/UserFoodHistory.java
  src/main/java/com/cloudbread/domain/user/domain/enums/MealType.java
  src/main/java/com/cloudbread/domain/user/domain/repository/UserFoodHistoryRepository.java
  src/main/java/com/cloudbread/domain/user/dto/UserRequestDto.java
  src/main/java/com/cloudbread/global/common/code/status/SuccessStatus.java
  src/main/java/com/cloudbread/global/config/RestTemplateConfig.java
  src/main/resources/application.yml
Labels: ✏️ feature

#52 [fix] : pr 에러 수정
  src/main/java/com/cloudbread/global/common/code/status/SuccessStatus.java
Labels: 🔨 fix

#56 [feat/#47] :음식 후보 3개 중 1개 선택 (FE -> BE) api 추가
  src/main/java/com/cloudbread/domain/photo_analyses/api/PhotoAnalysisRestController.java
  src/main/java/com/cloudbread/domain/photo_analyses/application/PhotoAnalysisService.java
  src/main/java/com/cloudbread/domain/photo_analyses/application/PhotoAnalysisServiceImpl.java
  src/main/java/com/cloudbread/domain/photo_analyses/domain/entity/PhotoAnalysis.java
  src/main/java/com/cloudbread/domain/photo_analyses/dto/PhotoAnalysisRequest.java
  src/main/java/com/cloudbread/domain/photo_analyses/dto/PhotoAnalysisResponse.java
Labels: ✏️ feature

#59 [feat/#46] 오늘의 AI 추천 식단 생성/조회
  src/main/java/com/cloudbread/.DS_Store
  src/main/java/com/cloudbread/domain/.DS_Store
  src/main/java/com/cloudbread/domain/mealplan/.DS_Store
  src/main/java/com/cloudbread/domain/mealplan/application/MealPlanServiceImpl.java
  src/main/java/com/cloudbread/domain/mealplan/client/FastApiMealPlanClient.java
  src/main/java/com/cloudbread/domain/mealplan/converter/MealPlanConverter.java
  src/main/java/com/cloudbread/domain/mealplan/coverter/MealPlanConverter.java
  src/main/java/com/cloudbread/domain/mealplan/domain/entity/MealPlan.java
  src/main/java/com/cloudbread/domain/mealplan/domain/entity/MealPlanItem.java
  src/main/java/com/cloudbread/domain/mealplan/domain/repository/MealPlanRepository.java
  src/main/java/com/cloudbread/domain/mealplan/dto/MealPlanResponseDto.java
  src/main/java/com/cloudbread/global/common/code/status/SuccessStatus.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: ✏️ feature

#60 [feat/#58] : 식단 추가 api
  src/main/java/com/cloudbread/domain/food_history/api/FoodHistoryRestController.java
  src/main/java/com/cloudbread/domain/food_history/application/FoodHistoryService.java
  src/main/java/com/cloudbread/domain/food_history/application/FoodHistoryServiceImpl.java
  src/main/java/com/cloudbread/domain/food_history/dto/FoodHistoryRequest.java
  src/main/java/com/cloudbread/domain/food_history/dto/FoodHistoryResponse.java
  src/main/java/com/cloudbread/domain/user/domain/entity/UserFoodHistory.java
  src/main/java/com/cloudbread/global/common/code/status/SuccessStatus.java
Labels: ✏️ feature

#62 [feat/#51] 오늘의 영양분석 조회
  src/main/java/com/cloudbread/domain/food/domain/repository/FoodNutrientRepository.java
  src/main/java/com/cloudbread/domain/nutrition/api/UserNutritionController.java
  src/main/java/com/cloudbread/domain/nutrition/application/UserNutritionStatsService.java
  src/main/java/com/cloudbread/domain/nutrition/application/UserNutritionStatsServiceImpl.java
  src/main/java/com/cloudbread/domain/nutrition/dto/TodayNutrientsStatsDto.java
  src/main/java/com/cloudbread/domain/nutrition/model/NutrientCalculationResult.java
  src/main/java/com/cloudbread/domain/user/domain/repository/UserFoodHistoryRepository.java
  src/main/java/com/cloudbread/global/common/code/status/SuccessStatus.java
Labels: ✏️ feature

#64 [feat/#63] 캘린더전체조회
  src/main/java/com/cloudbread/domain/food_history/api/FoodHistoryRestController.java
  src/main/java/com/cloudbread/domain/food_history/application/FoodHistoryService.java
  src/main/java/com/cloudbread/domain/food_history/application/FoodHistoryServiceImpl.java
  src/main/java/com/cloudbread/domain/food_history/dto/DayMealCountDto.java
  src/main/java/com/cloudbread/domain/food_history/dto/DayMealRecord.java
  src/main/java/com/cloudbread/domain/food_history/dto/FoodHistoryCalendarDto.java
  src/main/java/com/cloudbread/domain/user/domain/repository/UserFoodHistoryRepository.java
  src/main/java/com/cloudbread/global/common/code/status/ErrorStatus.java
  src/main/java/com/cloudbread/global/common/code/status/SuccessStatus.java
Labels: ✏️ feature

#68 [feat/#66] 캘린더 상세 조회
  .DS_Store
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/.DS_Store
  src/main/java/com/.DS_Store
  src/main/java/com/cloudbread/.DS_Store
  src/main/java/com/cloudbread/domain/.DS_Store
  src/main/java/com/cloudbread/domain/food/domain/repository/FoodNutrientRepository.java
  src/main/java/com/cloudbread/domain/food_history/api/FoodHistoryRestController.java
  src/main/java/com/cloudbread/domain/food_history/application/FoodHistoryService.java
  src/main/java/com/cloudbread/domain/food_history/application/FoodHistoryServiceImpl.java
  src/main/java/com/cloudbread/domain/food_history/dto/FoodHistoryResponse.java
  src/main/java/com/cloudbread/domain/nutrition/application/UserNutritionStatsServiceImpl.java
  src/main/java/com/cloudbread/domain/nutrition/constant/RecommendedNutrientConstants.java
  src/main/java/com/cloudbread/domain/user/domain/repository/UserFoodHistoryRepository.java
  src/main/java/com/cloudbread/global/common/code/status/ErrorStatus.java
  src/main/java/com/cloudbread/global/common/code/status/SuccessStatus.java
Labels: ✏️ feature

#69 [fix/#67] : 영양분석 후 챗봇 api
  src/main/java/com/cloudbread/domain/chat/nutrients/application/NutritionChatServiceImpl.java
  src/main/java/com/cloudbread/domain/chat/nutrients/dto/ai/AiChatRequest.java
  src/main/java/com/cloudbread/domain/food/domain/entity/Food.java
Labels: 🔨 fix

#72 [Feat/#71] 챗봇 메인화면 api
  src/main/java/com/cloudbread/domain/chat/main/api/AiGeneralChatRestController.java
  src/main/java/com/cloudbread/domain/chat/main/application/AiGeneralChatService.java
  src/main/java/com/cloudbread/domain/chat/main/application/AiGeneralChatServiceImpl.java
  src/main/java/com/cloudbread/domain/chat/main/application/session_store/AiInMemorySessionStore.java
  src/main/java/com/cloudbread/domain/chat/main/application/session_store/AiSessionContext.java
  src/main/java/com/cloudbread/domain/chat/main/application/session_store/AiSessionStore.java
  src/main/java/com/cloudbread/domain/chat/main/dto/AiGeneralChatRequestGen.java
  src/main/java/com/cloudbread/domain/chat/main/dto/AiGeneralChatResponseGen.java
  src/main/java/com/cloudbread/domain/chat/main/exception/InvalidTopicException.java
  src/main/java/com/cloudbread/domain/chat/main/exception/MissingTopicException.java
  src/main/java/com/cloudbread/domain/chat/nutrients/application/user_profile/UserProfileServiceImpl.java
  src/main/java/com/cloudbread/global/common/code/status/ErrorStatus.java
Labels: ✏️ feature

#73 [feat/70] 오늘의 영양 요약
  src/main/java/com/cloudbread/domain/food/domain/repository/FoodNutrientRepository.java
  src/main/java/com/cloudbread/domain/nutrition/api/UserNutritionController.java
  src/main/java/com/cloudbread/domain/nutrition/application/UserNutritionStatsService.java
  src/main/java/com/cloudbread/domain/nutrition/application/UserNutritionStatsServiceImpl.java
  src/main/java/com/cloudbread/domain/nutrition/dto/TodayNutrientsStatsDto.java
  src/main/java/com/cloudbread/domain/nutrition/dto/TodayNutrientsSummaryResponse.java
  src/main/java/com/cloudbread/domain/nutrition/model/NutrientCalculationResult.java
  src/main/java/com/cloudbread/domain/user/domain/repository/UserFoodHistoryRepository.java
  src/main/java/com/cloudbread/domain/user/domain/repository/UserRepository.java
  src/main/java/com/cloudbread/global/common/code/status/ErrorStatus.java
  src/main/java/com/cloudbread/global/common/code/status/SuccessStatus.java
Labels: ✏️ feature

#75 [Feat/#74] 영양소밸런스
  src/main/java/com/cloudbread/domain/.DS_Store
  src/main/java/com/cloudbread/domain/food/domain/repository/FoodNutrientRepository.java
  src/main/java/com/cloudbread/domain/nutrition/.DS_Store
  src/main/java/com/cloudbread/domain/nutrition/api/UserNutritionController.java
  src/main/java/com/cloudbread/domain/nutrition/application/UserNutritionStatsService.java
  src/main/java/com/cloudbread/domain/nutrition/application/UserNutritionStatsServiceImpl.java
  src/main/java/com/cloudbread/domain/nutrition/constant/RecommendedNutrientConstants.java
  src/main/java/com/cloudbread/domain/nutrition/dto/NutritionBalanceResponse.java
  src/main/java/com/cloudbread/domain/nutrition/dto/TodayNutrientsStatsDto.java
  src/main/java/com/cloudbread/global/common/code/status/ErrorStatus.java
  src/main/java/com/cloudbread/global/common/code/status/SuccessStatus.java
Labels: ✏️ feature
